# Site settings
title: YueYue
SEOTitle: 孙悦的博客|YueSun
header-img: img/home-bg.png
email: nwpusunyue@gmail.com
description: "Student of NPU"
keyword: "孙悦,YueSun"
url: "https://www.shun-fu.cn"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
weibo_username:     nwpusunyue
zhihu_username:     nwpusunyue
github_username:    nwpusunyue
twitter_username:   nwpusunyue
facebook_username:  nwpusunyue
linkedin_username:  nwpusunyue



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`


# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
disqus_username: nwpusunyue

# Netease setttings
netease_comment: false



# Analytics settings
# Baidu Analytics 
ba_track_id: 0d0b167521b3997c1f2c67c128dfcc78

# Google Analytics
ga_track_id: 'UA-111963608-1'            # Format: UA-xxxxxx-xx
ga_domain: nwpusunyue.github.io



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "感想心得，读书笔记<br>代码教程，研究思路"
sidebar-avatar: /img/yue.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
    #     title: "Su",
    #     href: "http://su.gallery/"
    # },{
        title: "Song",
        href: "http://songhexiang.github.io"
    },{
        title: "Lu",
        href: "http://shangqilu.github.io"
    },{
        title: "Hu",
        href: "http://prohuper.github.io"
    }
]
